### ISSUE TITLE
Rewrite app guillotine to provide a global headless API (not bound to sites)

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-guillotine#107]
In order to provide an easy-to-access headless API for XP, we will make some significant changes to the Guilllotine application:
We will basically keep the same functionality as we have today for lib-guillotine (embedding within site apps), but the guillotine app itself will be changed to offer a global (or project/branch scoped) version of the API

The basic concepts are as follows:

- [x] App guillotine cannot be added to a site anymore (to do this, one has to use lib-guillotine) https://github.com/enonic/lib-guillotine/issues/224
- [x] Should offer an in-project-context Content Studio API tab (with support for querying per branch) https://github.com/enonic/lib-guillotine/issues/226
- [ ] It will offer an endpoint that is future proof (think about future versioning etc)
- [x] It should offer a read-only API similar to what we already have, 
- [ ] but additionally support "multi-repo" capabilities
- [x] It should easily be possible to secure the API efficiently using vhosts/idproviders - 
- [ ] and potentially expose just specific repos/branches as well
- [x] Should provide the same functionality of lib-guillotine and site engine - including image service https://github.com/enonic/lib-guillotine/issues/228
- [ ] Support API tokens that limits access to the API (i.e. specific project/branch etc)
- [x] How to deal with URL fields? Just remove them? pageUrl essentially does not exist in this context! https://github.com/enonic/lib-guillotine/issues/228
- [ ] Consider if the API can be extended or not? (i.e. more root fields?) using other apps - but not needed right now.

Some Initial thoughts:

- Global: `/webapp/guillotine/` (pass headers to filter repos)
- Scoped: `/webapp/guilllotine/<project>/<branch>`
- Versioning - using headers or url path? i.e. `/webapp/guillotine/v1/..`
- Which apps/content types should be in the schema if you only access a specific project? (currently apps are not pinned to projects, only sites)

<img width="1012" alt="Screenshot 2022-01-30 at 13 12 47" src="https://user-images.githubusercontent.com/482228/151699109-a873f86f-e3a5-4e5c-8bb7-71298b8bc1ad.png">
Rudimentary idea of how this will integrated with Content Studio
- Do we need to provide an admin app (tool) for guillotine as well? I.e. multi-repo query interface from back-office?
- Are there other considerations?

**Comment by rymsha** [comment]
GA installed -> It appears in XP Menu -> All installed apps scanned to generate schema
