### ISSUE TITLE
Guillotine 3

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/app-guillotine#69]
Changes requested
- [x] Create a library lib-graphql-playground
- [x] Adapt app-guillotine to include this library
- [x] Display components as flat list. Similar to the way they are serialized
- [x] Add additional check
  - Fields: creator, modifier, owner, permissions
  - Role required: cms.cm.app, cms.admin, system.admin
- [x] Remove site path filtering on reference resolutions (ContentSelector, MediaUploader, AttachmentUploader, ImageSelector, ImageUploader)
